NMBP_Portal/ViewModels/NewsFormViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace NMBP_Portal.ViewModels
{
    public class NewsFormViewModel
    {
        public string Headline { get; set; }

        public string Text { get; set; }

        public string Author { get; set; }

        [Required]
        public string Picture { get; set; }
    }
}

NMBP_Portal/Controllers/PortalController.cs
using System.Web;
using System.Web.Mvc;
using DataAccess;
using DataAccess.Models;
using NMBP_Portal.ViewModels;

namespace NMBP_Portal.Controllers
{
    public class PortalController : Controller
    {
        private readonly MongoDatabase db = new MongoDatabase();

        public ActionResult Index()
        {
            var result = db.GetNews(10);
            return View(result);
        }

        public ActionResult AddNews()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddComment(int id, string comment)
        {
            db.AddComment(id, comment);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddNews(NewsFormViewModel model, HttpPostedFileBase upload)
        {
            var news = new News
            {
                Headline = model.Headline,
                Text = model.Text,
                Author = model.Author 
            };

            if (upload != null && upload.ContentLength > 0)
            {
                using (var reader = new System.IO.BinaryReader(upload.InputStream))
                {
                    news.Picture = reader.ReadBytes(upload.ContentLength);
                }
            }

            db.AddNews(news);

            return RedirectToAction("Index");
        }
    }
}

NMBP_Portal/Views/Portal/AddNews.cshtml
@model NMBP_Portal.ViewModels.NewsFormViewModel
@{
    ViewBag.Title = "Add News";
}
<h2>Add News</h2>
@using (Html.BeginForm("AddNews", "Portal", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Headline, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Headline, new { htmlAttributes = new { @class = "form-control" , @style = "width: 100%; max-width: 100%;" } })
                @Html.ValidationMessageFor(model => model.Headline, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text, new { @class = "form-control", rows = 20, @style = "width: 100%; max-width: 100%;" })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control", @style = "width: 100%; max-width: 100%;" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Picture" name="upload" />
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NMBP_Portal/Views/Portal/Index.cshtml
@model IEnumerable<DataAccess.Models.News>
@{
    ViewBag.Title = "Index";
}
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<h1>News</h1>
@foreach (var item in Model)
{
    <div class="w3-row">

        <div class="w3-col m6">
            <div class="w3-card-4 w3-margin w3-white">
                <div class="w3-container">
                    @{
                        string base64 = Convert.ToBase64String(item.Picture);
                        var imgSrc = $"data:image/gif;base64,{base64}";
                    }
                    <img src="@imgSrc" class="img-rounded" style="width: 300px;  margin-top:10%" align="middle" />
                    <h3><b>@item.Headline</b>
                    </h3>
                    <h5>Author : @item.Author</h5>
                    <hr>
                </div>

                <div class="w3-container">
                    <div class="col-lg-12">
                        @item.Text
                        <hr>
                    </div>
                    <div class="w3-container">
                        <ul class="list-group">
                            @if (item.Comments != null)
                            {
                                foreach (var comment in item.Comments)
                                {
                                    <li>@comment.Timestamp : @comment.Text</li>
                                }
                            }
                        </ul>
                        @using (Html.BeginForm("AddComment", "Portal", FormMethod.Post))
                        {

                            <input type="hidden" value="@item.Id" name="id" />
                            <div class="form-group">
                                <input type="text" class="form-control" name="comment" placeholder="Comment" required>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Add comment" class="btn btn-primary" />
                            </div>
                        }
                    </div>
                </div>
            </div>
            <hr>
        </div>

    </div>
}

NMBP_Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NMBP_Portal", "Index", "Portal", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Current News", "Index", "Portal")</li>
                    <li>@Html.ActionLink("Add News", "AddNews", "Portal")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>